name: " Testing the workflow"
on: 
 workflow_dispatch

jobs:
  terraformplan:
    name: Terraform initing
    runs-on: ubuntu-latest
    defaults:
     run:
      shell: bash
      working-directory: ./DEV
    steps:
     - name: checkout to git repo
       uses: actions/checkout@v3
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
       with:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
        
     - name: Terraform init
       id: init
       run: terraform init
     - name: terrform plan
       id: plan
       run: terraform plan
    
