name: " Testing the workflow"
on: 
 workflow_dispatch
permissions:
  id-token: write
  contents: read

jobs:
  terraformplan:
    name: Terraform initing
    runs-on: ubuntu-latest
    environment: 
     name: DEV
    defaults:
     run:
      shell: bash
      working-directory: ./DEV
    steps:
     - name: checkout to git repo
       uses: actions/checkout@v3
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
     - name: Azure login
       uses: azure/login@v2
    
       with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     - name: Terraform init
       id: init
       run: terraform init
     - name: terrform plan
       id: plan
       run: terraform plan
    
